// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avhpkknihqohyysqeahb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2aHBra25paHFvaHl5c3FlYWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTA2NjIsImV4cCI6MjA2MDc4NjY2Mn0.UQSmY4OgoJUJ0I6GN-oNB4jcsOKS98EtftjbQPzD-j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);